refs #1 debug

diff --git a/action.yml b/action.yml
--- a/action.yml
+++ b/action.yml
@@ -33,8 +33,8 @@ runs:
           exit 1
         fi
         git log --stat -1 --pretty=format:""
-        echo $(git log --stat -1 --pretty=format:"" | grep -o -E "$inputs.source/[^/]+\.txt")
-        $(git log --stat -1 --pretty=format:"" | grep -o -E "$inputs.source/[^/]+\.txt") || { echo "Error: Failed to retrieve changed files"; exit 1; }
+        echo $(git log --stat -1 --pretty=format:"" | grep -o -E "${{ inputs.source }}/[^/]+\.txt")
+        $(git log --stat -1 --pretty=format:"" | grep -o -E "${{ inputs.source }}/[^/]+\.txt") || { echo "Error: Failed to retrieve changed files"; exit 1; }
     - name: Docker Set Up
       shell: bash
       run: |
