refs #1 Error: Process completed with exit code 1.

diff --git a/action.yml b/action.yml
--- a/action.yml
+++ b/action.yml
@@ -42,8 +42,6 @@ runs:
     - name: Create Destination Folder
       shell: bash
       run: |
-        ls -l
-        ls -l text
         if [ ! -d "${{ inputs.destination }}" ]; then
           mkdir -p "${{ inputs.destination }}"
         fi
@@ -51,10 +49,7 @@ runs:
     - name: Generate Audio
       shell: bash
       run: |
-        git log --stat -1 --pretty=format:""
-        git log --stat -1 --pretty=format:"" | grep -o -E '${{ inputs.source }}/[^/]+\.txt'
-
-        changed_files=$(git log --stat -1 --pretty=format:"" | grep -o -E '${{ inputs.source }}/[^/]+\.txt') || { echo "Error: Failed to retrieve changed files"; exit 1; }
+        changed_files=$(git log --stat -1 --pretty=format:"" | grep -o -E '$inputs.source/[^/]+\.txt') || { echo "Error: Failed to retrieve changed files"; exit 1; }
 
         if [ -z "$changed_files" ]; then
           echo "No .txt files found in the specified path."
