refs #1 basename

diff --git a/action.yml b/action.yml
--- a/action.yml
+++ b/action.yml
@@ -33,9 +33,9 @@ runs:
           exit 1
         fi
         git log --stat -1 --pretty=format:""       
-        rep=$(git log --stat -1 --pretty=format:"" | grep -o -E '${{ inputs.source }}/[^/]+\.txt' | xargs realpath --relative-to="$PWD")
+        rep=$(git log --stat -1 --pretty=format:"" | grep -o -E 'basename ${{ inputs.source }}/[^/]+\.txt' | xargs realpath --relative-to="$PWD")
         echo $rep
-        changed_files=$(git log --stat -1 --pretty=format:"" | grep -o -E '${{ inputs.source }}/[^/]+\.txt' | xargs realpath --relative-to="$PWD") || { echo "Error: Failed to retrieve changed files"; exit 1; }
+        changed_files=$(git log --stat -1 --pretty=format:"" | grep -o -E 'basename ${{ inputs.source }}/[^/]+\.txt' || { echo "Error: Failed to retrieve changed files"; exit 1; }
         echo "changed_files=${changed_files}" >> "$GITHUB_ENV"
     - name: Docker Set Up
       shell: bash
