refs #1 debug

diff --git a/action.yml b/action.yml
--- a/action.yml
+++ b/action.yml
@@ -36,9 +36,12 @@ runs:
           exit 1
         fi
         git log --stat -1 --pretty=format:""
-        git log --stat -1 --pretty=format:"" | grep -o -E 'text/[^/]+\.txt')
-        git log --stat -1 --pretty=format:"" | grep -o -E '${{ inputs.source }}/[^/]+\.txt')
-        changed_files=$(git log --stat -1 --pretty=format:"" | grep -o -E '${{ inputs.source }}/[^/]+\.txt') || { echo "Error: Failed to retrieve changed files"; exit 1; }
+        rep = $(git log --stat -1 --pretty=format:"" | grep -o -E 'text/[^/]+\.txt')
+        echo rep
+        rep = $(git log --stat -1 --pretty=format:"" | grep -o -E '${{ inputs.source }}/[^/]+\.txt')
+        echo rep
+        rep = changed_files=$(git log --stat -1 --pretty=format:"" | grep -o -E '${{ inputs.source }}/[^/]+\.txt') || { echo "Error: Failed to retrieve changed files"; exit 1; }
+        echo rep
         echo "changed_files=${changed_files}" >> "$GITHUB_ENV"
     - name: Docker Set Up
       shell: bash
