refs #1 debug

diff --git a/action.yml b/action.yml
--- a/action.yml
+++ b/action.yml
@@ -28,12 +28,16 @@ runs:
     - name: Check Source Directory
       shell: bash
       run: |
+        pwd
+        echo ${{ inputs.source }}
+        ls -l ${{ inputs.source }}
         if [ ! -d "${{ inputs.source }}" ]; then
           echo "Error: Source directory '${{ inputs.source }}' does not exist."
           exit 1
         fi
+        ls -l ${{ inputs.source }}
         git log --stat -1 --pretty=format:""
-        changed_files=$(git log --stat -1 --pretty=format:"" | grep -o -E "${{ inputs.source }}/[^/]+\.txt") || { echo "Error: Failed to retrieve changed files"; exit 0; }
+        changed_files=$(git log --stat -1 --pretty=format:"" | grep -o -E "${{ inputs.source }}/[^/]+\.txt") || { echo "Error: Failed to retrieve changed files"; exit 1; }
         echo "changed_files=${changed_files}" >> "$GITHUB_ENV"
     - name: Docker Set Up
       shell: bash
