refs #1 debug

diff --git a/action.yml b/action.yml
--- a/action.yml
+++ b/action.yml
@@ -33,8 +33,8 @@ runs:
           exit 1
         fi
         git log --stat -1 --pretty=format:""
-        echo $(git log --stat -1 --pretty=format:"" | grep -o -E "${{ inputs.source }}/[^/]+\.txt")
-        $(git log --stat -1 --pretty=format:"" | grep -o -E "${{ inputs.source }}/[^/]+\.txt") || { echo "Error: Failed to retrieve changed files"; exit 1; }
+        changed_files=$(git log --stat -1 --pretty=format:"" | grep -o -E "${{ inputs.source }}/[^/]+\.txt") || { echo "Error: Failed to retrieve changed files"; exit 0; }
+        echo "changed_files=${changed_files}" >> "$GITHUB_ENV"
     - name: Docker Set Up
       shell: bash
       run: |
@@ -52,8 +52,6 @@ runs:
     - name: Generate Audio
       shell: bash
       run: |
-        changed_files=$(git log --stat -1 --pretty=format:"" | grep -o -E "$inputs.source/[^/]+\.txt") || { echo "Error: Failed to retrieve changed files"; exit 1; }
-
         if [ -z "$changed_files" ]; then
           echo "No .txt files found in the specified path."
           exit 0
