refs #1 Error: Process completed with exit code 123.

diff --git a/action.yml b/action.yml
--- a/action.yml
+++ b/action.yml
@@ -32,10 +32,10 @@ runs:
           echo "Error: Source directory '${{ inputs.source }}' does not exist."
           exit 1
         fi
-        git log --stat -1 --pretty=format:""       
-        rep=$(git log --stat -1 --pretty=format:"" | grep -o -E 'basename ${{ inputs.source }}/[^/]+\.txt' | xargs realpath --relative-to="$PWD")
-        echo $rep
-        changed_files=$(git log --stat -1 --pretty=format:"" | grep -o -E 'basename ${{ inputs.source }}/[^/]+\.txt' || { echo "Error: Failed to retrieve changed files"; exit 1; }
+        git log --stat -1 --pretty=format:"" 
+        ${_source} = basename ${{ inputs.source }}
+        echo ${_source}
+        changed_files=$(git log --stat -1 --pretty=format:"" | grep -o -E '${_source}/[^/]+\.txt' || { echo "Error: Failed to retrieve changed files"; exit 1; }
         echo "changed_files=${changed_files}" >> "$GITHUB_ENV"
     - name: Docker Set Up
       shell: bash
