refs #1 Error: Process completed with exit code 1.

diff --git a/action.yml b/action.yml
--- a/action.yml
+++ b/action.yml
@@ -42,7 +42,13 @@ runs:
     - name: Generate Audio
       shell: bash
       run: |
-        changed_files=$(git log --stat -1 --pretty=format:"" | grep -o -E '${{ inputs.source }}/[^/]+\.txt')
+        changed_files=$(git log --stat -1 --pretty=format:"" | grep -o -E '${{ inputs.source }}/[^/]+\.txt') || { echo "Error: Failed to retrieve changed files"; exit 1; }
+
+        if [ -z "$changed_files" ]; then
+          echo "No .txt files found in the specified path."
+          exit 0
+        fi
+
         echo "$changed_files"
 
         for filename in $changed_files
