refs #1 debug

diff --git a/action.yml b/action.yml
--- a/action.yml
+++ b/action.yml
@@ -35,9 +35,7 @@ runs:
           echo "Error: Source directory '${{ inputs.source }}' does not exist."
           exit 1
         fi
-        ls -l ${{ inputs.source }}
-        git log --stat -1 --pretty=format:""
-        changed_files=$(git log --stat -1 --pretty=format:"" | grep -o -E "${{ inputs.source }}/[^/]+\.txt") || { echo "Error: Failed to retrieve changed files"; exit 1; }
+        changed_files=$(git log --stat -1 --pretty=format:"" | grep -o -E '${{ inputs.source }}/[^/]+\.txt') || { echo "Error: Failed to retrieve changed files"; exit 1; }
         echo "changed_files=${changed_files}" >> "$GITHUB_ENV"
     - name: Docker Set Up
       shell: bash
