refs #1 Error: Process completed with exit code 1.

diff --git a/action.yml b/action.yml
--- a/action.yml
+++ b/action.yml
@@ -25,6 +25,13 @@ runs:
       uses: actions/checkout@v4
       with:
         fetch-depth: 2
+    - name: Check Source Directory
+      shell: bash
+      run: |
+        if [ ! -d "${{ inputs.source }}" ]; then
+          echo "Error: Source directory '${{ inputs.source }}' does not exist."
+          exit 1
+        fi
     - name: Docker Set Up
       shell: bash
       run: |
